import React from 'react';

import { Hourly, } from '../../components/weather/Hourly';
import { Constants, } from '../../Constants';

export default {
    title     : 'Weather/Hourly',
    component : Hourly,
    argTypes  : {
        providerId : {
            options : Constants.WEATHER_PROVIDERS.map(provider => provider.id),
            control : {
                type : 'select',
            },
        },
        unit       : {
            options : Constants.UNITS.map(unit => unit.value),
            control : {
                type : 'select',
            },
        },
        forecast   : {
            options : Constants.FORECAST_TYPES.map(forecast => forecast.value),
            control : {
                type : 'select',
            },
        },
        timeFormat : {
            options : [
                'HH',
                'ha',
            ],
            control : {
                type : 'select',
            },
        },
    },
};

const Template = args => <Hourly {...args} />;

export const Basic = Template.bind({});
Basic.args = {
    size       : {
        width  : 400,
        height : 200,
    },
    data       : [
        {
            'time'                : 1586336400000,
            'summary'             : 'Clear',
            'icon'                : 'clear-day',
            'precipIntensity'     : 0.1,
            'precipProbability'   : 0.1,
            'temperature'         : 22.96,
            'apparentTemperature' : 22.96,
            'dewPoint'            : 11.19,
            'humidity'            : 0.47,
            'pressure'            : 1015.7,
            'windSpeed'           : 2.68,
            'windGust'            : 6.1,
            'windBearing'         : 34,
            'cloudCover'          : 0.2,
            'uvIndex'             : 1,
            'visibility'          : 10.413,
            'ozone'               : 283.7,
        }, {
            'time'                : 1586340000000,
            'summary'             : 'Clear',
            'icon'                : 'clear-day',
            'precipIntensity'     : 0.3,
            'precipProbability'   : 0.7,
            'temperature'         : 22.8,
            'apparentTemperature' : 22.8,
            'dewPoint'            : 11.26,
            'humidity'            : 0.48,
            'pressure'            : 1016,
            'windSpeed'           : 2.54,
            'windGust'            : 5.92,
            'windBearing'         : 31,
            'cloudCover'          : 0.23,
            'uvIndex'             : 0,
            'visibility'          : 10.413,
            'ozone'               : 283.4,
        }, {
            'time'                : 1586343600000,
            'summary'             : 'Partly Cloudy',
            'icon'                : 'partly-cloudy-night',
            'precipIntensity'     : 0.2,
            'precipProbability'   : 0.3,
            'temperature'         : 22.52,
            'apparentTemperature' : 22.52,
            'dewPoint'            : 11.91,
            'humidity'            : 0.51,
            'pressure'            : 1016.4,
            'windSpeed'           : 2.47,
            'windGust'            : 5.67,
            'windBearing'         : 36,
            'cloudCover'          : 0.33,
            'uvIndex'             : 0,
            'visibility'          : 11.839,
            'ozone'               : 282.8,
        }, {
            'time'                : 1586347200000,
            'summary'             : 'Mostly Cloudy',
            'icon'                : 'partly-cloudy-night',
            'precipIntensity'     : 0,
            'precipProbability'   : 0,
            'temperature'         : 21.63,
            'apparentTemperature' : 21.63,
            'dewPoint'            : 14.71,
            'humidity'            : 0.65,
            'pressure'            : 1017,
            'windSpeed'           : 3.22,
            'windGust'            : 5.45,
            'windBearing'         : 84,
            'cloudCover'          : 0.6,
            'uvIndex'             : 0,
            'visibility'          : 16.093,
            'ozone'               : 282.3,
        }, {
            'time'                : 1586350800000,
            'summary'             : 'Mostly Cloudy',
            'icon'                : 'partly-cloudy-night',
            'precipIntensity'     : 0,
            'precipProbability'   : 0,
            'temperature'         : 21.02,
            'apparentTemperature' : 21.12,
            'dewPoint'            : 16.29,
            'humidity'            : 0.74,
            'pressure'            : 1017.6,
            'windSpeed'           : 3.63,
            'windGust'            : 5.35,
            'windBearing'         : 99,
            'cloudCover'          : 0.72,
            'uvIndex'             : 0,
            'visibility'          : 16.093,
            'ozone'               : 281.9,
        }, {
            'time'                : 1586354400000,
            'summary'             : 'Mostly Cloudy',
            'icon'                : 'partly-cloudy-night',
            'precipIntensity'     : 0,
            'precipProbability'   : 0,
            'temperature'         : 20.94,
            'apparentTemperature' : 21.03,
            'dewPoint'            : 16.19,
            'humidity'            : 0.74,
            'pressure'            : 1018.2,
            'windSpeed'           : 3.42,
            'windGust'            : 5.28,
            'windBearing'         : 91,
            'cloudCover'          : 0.66,
            'uvIndex'             : 0,
            'visibility'          : 16.093,
            'ozone'               : 281.5,
        }, {
            'time'                : 1586358000000,
            'summary'             : 'Mostly Cloudy',
            'icon'                : 'partly-cloudy-night',
            'precipIntensity'     : 0,
            'precipProbability'   : 0,
            'temperature'         : 20.87,
            'apparentTemperature' : 20.94,
            'dewPoint'            : 16.02,
            'humidity'            : 0.74,
            'pressure'            : 1018.6,
            'windSpeed'           : 3.3,
            'windGust'            : 5.17,
            'windBearing'         : 87,
            'cloudCover'          : 0.62,
            'uvIndex'             : 0,
            'visibility'          : 16.093,
            'ozone'               : 281.3,
        }, {
            'time'                : 1586361600000,
            'summary'             : 'Partly Cloudy',
            'icon'                : 'partly-cloudy-night',
            'precipIntensity'     : 0,
            'precipProbability'   : 0,
            'temperature'         : 20.81,
            'apparentTemperature' : 20.85,
            'dewPoint'            : 15.79,
            'humidity'            : 0.73,
            'pressure'            : 1018.2,
            'windSpeed'           : 3.33,
            'windGust'            : 4.94,
            'windBearing'         : 85,
            'cloudCover'          : 0.59,
            'uvIndex'             : 0,
            'visibility'          : 16.093,
            'ozone'               : 281.3,
        },
    ],
    providerId : Constants.WEATHER_PROVIDERS[0].id,
    unit       : Constants.UNITS[0].value,
    forecast   : Constants.FORECAST_TYPES[0].value,
};


export const WithPrefix = Template.bind({});
WithPrefix.args = {
    ...Basic.args,
    temperaturePrefix : '🌡',
    humidityPrefix    : '💧',
    precipPrefix      : '🌧',
    windSpeedPrefix   : '🌬',
    uvIndexPrefix     : '☀️',
};
